### ISSUE TITLE
Travis test fails

### ISSUE THREAD

**Issue by stebogit** [stebogit/matrix-to-grid#1]
@DenisCarriere why do you think [tests](https://travis-ci.org/stebogit/matrix-to-grid/branches) do not pass in Trevis? It seems it can not find `test/out/5X5.geojson`, but it is in there!
They all pass OK when I run `npm test` 😞

**Comment by DenisCarriere** [comment]
Strange, looks good to me, I've sent a PR (looks like the indentation & end of line is different).

Travis is being slow today.
