### ISSUE TITLE
Output doesn't always match with `cellSize` value

### ISSUE THREAD

**Issue by stebogit** [stebogit/matrix-to-grid#3]
The same input `matrix`+`cellSize` at different latitudes returns different distance between points. Distance does match `cellSize` at low latitudes:

### Example: 
`origin` at 47˚N, `cellSize` 25km (~15.5 miles) - [`3x4.json`](https://github.com/stebogit/matrix-to-grid/blob/dev/test/in/3x4.json):
![screen shot 2017-04-30 at 11 12 20 pm](https://cloud.githubusercontent.com/assets/12717225/25573751/1470fe4a-2dfd-11e7-8dca-af1526603037.png)

`origin` at 0˚N, `cellSize` 25km  (~15.5 miles) - [`3x4-at-0.json`](https://github.com/stebogit/matrix-to-grid/blob/dev/test/in/3x4-at-0.json):
![screen shot 2017-04-30 at 11 28 13 pm](https://cloud.githubusercontent.com/assets/12717225/25573754/182aa3ce-2dfd-11e7-8224-9dde053a02c9.png)

**Comment by stebogit** [comment]
@DenisCarriere I introduced `global-mercator` and I finally get a nice output, with all the points in a row at the same latitude. However even with that tool I encounter the issue where distances at higher latitudes are not consistent.
Am I not [using](https://github.com/stebogit/matrix-to-grid/blob/dev/index.js#L59-L85) `global-mercator` correctly?

**Comment by DenisCarriere** [comment]
It does look like your using `global-mercator` correctly, after reading over Web Mercator (meters) it describes the projection as [conformal](https://en.wikipedia.org/wiki/Conformal_map), meaning it only preserves angles which might be why you're getting that distortion in the higher latitudes.

I believe this is one of the main reasons why TurfJS doesn't want to get into re-projections, however you can experiment with different projections using [`proj4js`](https://github.com/proj4js/proj4js).

Trial and error with this one 👍

**Comment by DenisCarriere** [comment]
+1 that's cool that you got it working with geodesy, I'm currently using that library in another project
